import { TokenData } from "@/hooks/useWebSocketMock";

export const dummyTokens: TokenData[] = [
  // New Pairs
  {
    id: "1",
    tokenAddress: "D6WG...pump",
    tokenName: "Hot Crypto Girl",
    tokenSymbol: "HCG",
    tokenImage: "https://picsum.photos/seed/hot-crypto-girl/200/200",
    timeAgo: "6s",
    holders: 253,
    proTraders: 0,
    views: 0,
    holderPercent: 4,
    chefPercent: 3,
    snipePercent: 14,
    ghostPercent: 4,
    boxesPercent: 0,
    marketCap: 3690,
    volume: 584,
    solanaPrice: 0.016,
    transactions: 8,
  },
  {
    id: "2",
    tokenAddress: "DTg6...pump",
    tokenName: "F2026",
    tokenSymbol: "F2026",
    tokenImage: "https://picsum.photos/seed/f2026/200/200",
    timeAgo: "15s",
    holders: 1,
    proTraders: 1,
    views: 4,
    holderPercent: 1,
    chefPercent: 1,
    snipePercent: 1,
    ghostPercent: 1,
    boxesPercent: 0,
    marketCap: 1210,
    volume: 84,
    solanaPrice: 0.026,
    transactions: 14,
  },
  {
    id: "3",
    tokenAddress: "7dF9...pump",
    tokenName: "The Fatass Whale",
    tokenSymbol: "$TFW",
    tokenImage: "https://picsum.photos/seed/fatass-whale/200/200",
    timeAgo: "18s",
    holders: 2,
    proTraders: 2,
    views: 2,
    holderPercent: 2,
    chefPercent: 2,
    snipePercent: 2,
    ghostPercent: 2,
    boxesPercent: 0,
    marketCap: 1780,
    volume: 176,
    solanaPrice: 0.027,
    transactions: 16,
  },
  {
    id: "4",
    tokenAddress: "BT2W...pump",
    tokenName: "WHALE by https and whigga dev",
    tokenSymbol: "WHALE",
    tokenImage: "https://picsum.photos/seed/whale/200/200",
    timeAgo: "20s",
    holders: 0,
    proTraders: 0,
    views: 0,
    holderPercent: 0,
    chefPercent: "DS 4mo",
    snipePercent: 0,
    ghostPercent: 0,
    boxesPercent: 0,
    marketCap: 3430,
    volume: 2,
    solanaPrice: 0.025,
    transactions: 3,
  },
  {
    id: "5",
    tokenAddress: "4MKJ...7Rxg",
    tokenName: "pandu",
    tokenSymbol: "pandu",
    tokenImage: "https://picsum.photos/seed/pandu/200/200",
    timeAgo: "21s",
    holders: 19,
    proTraders: 0,
    views: 13,
    holderPercent: 19,
    chefPercent: 0,
    snipePercent: 13,
    ghostPercent: 19,
    boxesPercent: 0,
    marketCap: 520000,
    volume: 15000,
    solanaPrice: 0.02,
    transactions: 32,
  },
  // Final Stretch
  {
    id: "6",
    tokenAddress: "9tFC...nRNT",
    tokenName: "TikTok",
    tokenSymbol: "TikTok",
    tokenImage: "https://picsum.photos/seed/tiktok/200/200",
    timeAgo: "5m",
    holders: 253,
    proTraders: 0,
    views: 0,
    holderPercent: 19,
    chefPercent: 0,
    snipePercent: 6,
    ghostPercent: 19,
    boxesPercent: 0,
    marketCap: 700000,
    volume: 18000,
    solanaPrice: 0.024,
    transactions: 419,
  },
  {
    id: "7",
    tokenAddress: "3c9a...pump",
    tokenName: "The ELF On The Shelf",
    tokenSymbol: "ELF",
    tokenImage: "https://picsum.photos/seed/elf/200/200",
    timeAgo: "3h",
    holders: 54,
    proTraders: 0,
    views: 10,
    holderPercent: 54,
    chefPercent: "DS 10mo",
    snipePercent: 0,
    ghostPercent: 80,
    boxesPercent: 77,
    marketCap: 3430,
    volume: 775,
    solanaPrice: 0.02,
    transactions: 52,
  },
  {
    id: "8",
    tokenAddress: "3pra...c7V8",
    tokenName: "SENT Sentientd Bit Block",
    tokenSymbol: "SENT",
    tokenImage: "https://picsum.photos/seed/sent/200/200",
    timeAgo: "5m",
    holders: 21,
    proTraders: 0,
    views: 0,
    holderPercent: 21,
    chefPercent: 0,
    snipePercent: 0,
    ghostPercent: 40,
    boxesPercent: 0,
    marketCap: 6100,
    volume: 4000,
    solanaPrice: 0.029,
    transactions: 110,
  },
  // Migrated
  {
    id: "9",
    tokenAddress: "ZasZ...da4o",
    tokenName: "Mars Coin",
    tokenSymbol: "MARS",
    tokenImage: "https://picsum.photos/seed/mars/200/200",
    timeAgo: "7s",
    holders: 75,
    proTraders: 75,
    views: 2,
    holderPercent: 75,
    chefPercent: 75,
    snipePercent: 2,
    ghostPercent: 75,
    boxesPercent: 0,
    marketCap: 44400,
    volume: 11000,
    solanaPrice: 0.033,
    transactions: 23,
  },
  {
    id: "10",
    tokenAddress: "8QBo...onuL",
    tokenName: "PLIM",
    tokenSymbol: "PLIM",
    tokenImage: "https://picsum.photos/seed/plim/200/200",
    timeAgo: "1m",
    holders: 100,
    proTraders: 0,
    views: 9,
    holderPercent: 100,
    chefPercent: 0,
    snipePercent: 9,
    ghostPercent: 20,
    boxesPercent: 0,
    marketCap: 1340000,
    volume: 26000,
    solanaPrice: 0.024,
    transactions: 318,
  },
  {
    id: "11",
    tokenAddress: "3WMA...sL2s",
    tokenName: "test",
    tokenSymbol: "testtoken",
    tokenImage: "https://picsum.photos/seed/test/200/200",
    timeAgo: "1m",
    holders: 76,
    proTraders: 75,
    views: 44,
    holderPercent: 76,
    chefPercent: 75,
    snipePercent: 44,
    ghostPercent: 75,
    boxesPercent: 0,
    marketCap: 69900,
    volume: 14000,
    solanaPrice: 0.039,
    transactions: 123,
  },
  {
    id: "12",
    tokenAddress: "Ajdr...RnyE",
    tokenName: "The White Whale",
    tokenSymbol: "WhiteWhale",
    tokenImage: "https://picsum.photos/seed/white-whale/200/200",
    timeAgo: "2m",
    holders: 98,
    proTraders: 0,
    views: 5,
    holderPercent: 98,
    chefPercent: 0,
    snipePercent: 5,
    ghostPercent: 20,
    boxesPercent: 0,
    marketCap: 1300000,
    volume: 26000,
    solanaPrice: 0.027,
    transactions: 851,
  },
  // Additional tokens with same image for popover demo
  {
    id: "13",
    tokenAddress: "NVID...pump",
    tokenName: "NVIDIA SQUIRREL",
    tokenSymbol: "SQUIRREL",
    tokenImage: "https://picsum.photos/seed/nvidia-squirrel/200/200",
    timeAgo: "1y",
    holders: 150,
    proTraders: 0,
    views: 10,
    holderPercent: 50,
    chefPercent: 0,
    snipePercent: 10,
    ghostPercent: 0,
    boxesPercent: 0,
    marketCap: 3400,
    volume: 0,
    solanaPrice: 0.001,
    transactions: 3400,
  },
  {
    id: "14",
    tokenAddress: "NVID2...pump",
    tokenName: "NVIDIA SQUIRREL",
    tokenSymbol: "SQUIRREL",
    tokenImage: "https://picsum.photos/seed/nvidia-squirrel-2/200/200",
    timeAgo: "1y",
    holders: 200,
    proTraders: 0,
    views: 15,
    holderPercent: 60,
    chefPercent: 0,
    snipePercent: 15,
    ghostPercent: 0,
    boxesPercent: 0,
    marketCap: 3400,
    volume: 0,
    solanaPrice: 0.001,
    transactions: 3400,
  },
];
